[package]
name = "crdt_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
crdts = "7.3.2"
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"
memory-stats = "1.2.0"

[[bench]]
name = "benchmarks"
harness = false
